inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/*'
    - 'vendor/**/*'

# Indentation (5 spaces)
Layout/IndentationWidth:
  Width: 5
Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

# Style Guidelines
Style/For:
  EnforcedStyle: each
Style/UnlessElse:
  Enabled: true
Style/NegatedWhile:
  EnforcedStyle: invert
Style/DefWithParentheses:
  Enabled: true
Style/GlobalVars:
  AllowedVariables: []

# Naming Conventions
Naming/VariableName:
  EnforcedStyle: snake_case
Naming/MethodName:
  EnforcedStyle: snake_case
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/ConstantName:
  Enabled: true
Naming/PredicateName:
  AllowPrefixes: ['is_', 'has_', 'can_']
  AllowedMethods: []

# Rails-Specific Rules
Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true
Rails/EnumHash:
  Enabled: true
Rails/EnumUniqueness:
  Enabled: true
Rails/FindEach:
  Enabled: true
Rails/OutputSafety:
  Enabled: true

# View-related rules
Rails/RenderInline:
  Enabled: true

# Controller/Model/View Best Practices
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15

# Disable Conflicting or Unnecessary Cops
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false